spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  servlet:
    multipart:
      max-file-size: 100MB
  solr:
    host: 'http://116.56.134.166:8983/solr'
server:
  port: 9000
  tomcat:
    accesslog:
      enabled: true
    protocol-header: x-forwarded-proto
    remote-ip-header: x-forwarded-for
    uri-encoding: utf-8
logging:
  level:
    org.springframework.web: ERROR
    org.springframework.security: ERROR
    org.hibernate: ERROR
    com.natuty: DEBUG
debug: true





