version: '3'
services:
  mysql:
    image: mysql:5.5.50
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - webnet
networks:
  webnet:
