version: '3'
services:
  apiserver:
    build:
      context: ./
      dockerfile: Dockerfile
    image: local/apiserver:latest
    ports:
     - "9001:9000"
    networks:
      - my-net
networks:
  my-net:
    external:
      name: my-net
