spring:
  profiles:
    active: dev
  solr:
    host: 'http://116.56.134.166:8983/solr'
  rpcServer:
    endpoint: "http://120.77.182.188:3306/data"
server:
  port: 9000
  tomcat:
    accesslog:
      enabled: true
    protocol-header: x-forwarded-proto
    remote-ip-header: x-forwarded-for
    uri-encoding: utf-8
logging:
  level:
    org.springframework.web: ERROR
    org.springframework.security: ERROR
    org.hibernate: ERROR
    com.example.app: DEBUG
debug: true





