spring:
  datasource:
    url: jdbc:mysql://116.56.134.166:3306/news_recommend?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update


  profiles:
    active: dev
  solr:
    host: 'http://116.56.134.166:8983/solr'
server:
  port: 9002
  tomcat:
    accesslog:
      enabled: true
    protocol-header: x-forwarded-proto
    remote-ip-header: x-forwarded-for
    uri-encoding: utf-8
logging:
  level:
    org.springframework.web: ERROR
    org.springframework.security: ERROR
    org.hibernate: ERROR
    com.example.app: DEBUG
debug: true





